version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    volumes:
      - ./backend:/var/www
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: nginx_web
    ports:
      - "8888:80"  
    volumes:
      - ./backend:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3388:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    restart: always
    ports:
      - "8899:80"  # phpMyAdmin accesible en http://localhost:8899
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306

volumes:
  dbdata: